# Generated by Django 5.2.7 on 2025-10-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bytechatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='username',
            new_name='receiver',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
