# Generated by Django 5.2.7 on 2025-10-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bytechatapp', '0005_customuser_is_online_customuser_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
